@startuml

class Interval{
- initialTime : LocalDateTime
- endTime : LocalDateTime
- timeFormatter : DateTimeFormatter
- owner : Task
- time : Duration
+ Interval(owner : Task, begin : LocalDateTime , end : LocalDateTime, duration : Duration)
+ print()
+ stopTicking()
+ update(o : Observable ,arg : Object)
}

class Client{
+ {static} main(String[] args)
+ {static} simpleTest()
}
class Clock extends Observable{
- date : LocalDateTime
- timer : Timer
- clockTimer : Clock
- periodo : int
- Clock()
+ start()
+ stop()
}

class ElementVisitor implements Visitor{
+ visitProject(p : Project)
+ visitTask(t : Task)
}

abstract class Component{
- compName : String
- father : Project
- startDate : LocalDateTime
- endDate : LocalDateTime
- tagList : ArrayList<String>
+ Component (name : String, start : LocalDateTime, LocalDateTime : LocalDateTime, tags : ArrayList<String>)
+ Component(compName : String, father : Project , tagList : ArrayList<String>)
+ Component (compName : String, father : Project )
+ Component (name : String, tags : ArrayList<String>)
+ Component (name : String)
}

class Project extends Component{
+ compList : ArrayList<Component>
+ Project (name : String, start : LocalDateTime, LocalDateTime : LocalDateTime, tags : ArrayList<String>)
+ Project(compName : String, father : Project , tagList : ArrayList<String>)
+ Project (compName : String, father : Project )
+ Project (name : String, tags : ArrayList<String>)
+ Project (name : String)
+ addProject(p : Project)
+ addTask(t : Task)
+ toString() : String
}

class Task extends Component{
- intervalList : ArrayList<Interval>
+ Task (name : String, start : LocalDateTime, LocalDateTime : LocalDateTime, tags : ArrayList<String>)
+ Task (compName : String, father : Project , tagList : ArrayList<String>)
+ Task (compName : String, father : Project )
+ Task (name : String, tags : ArrayList<String>)
+ Task (name : String)
+ toString() : String
}

interface Visitor{
+ visitProject(p Project)
+ visitTask(t Task)
}

class Observer{
+ update(o : Observable, arg : Object)
}

Project *-right-> "0..*" Component
Interval --right--> "*..1" Task
Observable --down> Observer
Interval ..up|> Observer
Client --> Component
Visitor --left> Client
@enduml